[tool.bumpversion]
current_version = "0.0.1"
commit = true
message = "chore: bump version to {new_version}"
tag = true
tag_name = "v{new_version}"
tag_message = "Version {new_version}"
setup_hooks = [
  "git-cliff",
  "git add -- CHANGELOG.md",
]

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search = "## Unreleased"
replace = """
## Unreleased

## v{new_version} - {now:%Y-%m-%d}"""
