[tool.bumpversion]
current_version = "0.0.1"
commit = true
message = "chore: bump version to {new_version}"
tag = true
tag_name = "v{new_version}"
tag_message = "Version {new_version}"
setup_hooks = [
  "git-cliff --bump",
  "git add -- CHANGELOG.md",
]
