---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        entry: yamllint --strict
  - repo: https://github.com/flaudisio/pre-commit-hooks
    rev: v0.11.1
    hooks:
      - id: nomad-fmt
  - repo: local
    hooks:
      - id: nomad-pack-docs
        name: Nomad Pack docs
        description: Updates pack READMEs with useful pack information.
        entry: scripts/pre-commit/nomad-pack-docs.sh
        args:
          - --sort-by=required
          - --show=inputs
        language: script
        files: ^packs/.+/variables\.hcl$
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: shellcheck
