[tools]
git-cliff = "2"
hcl2json = "0.6"
nomad = "1"
nomad-pack = "0.4"
"pipx:bump-my-version" = "1"
shellcheck = "0.10"
terraform-docs = "0.20"

[tasks.pre-commit]
description = "Run pre-commit"
run = "pre-commit run --all-files --verbose --show-diff-on-failure --color always"

[tasks.fmt]
description = "Format files"
run = "nomad fmt -recursive ."
dir = "{{ cwd }}"

[tasks.update-changelogs]
description = "Update all pack changelogs"
run = """
  #!/usr/bin/env bash
  set -e
  for path in packs/* ; do
    [[ -d "$path" ]] || continue
    echo "--> $path" >&2
    git-cliff --include-path "${path}/**" --output "${path}/CHANGELOG.md"
  done
"""

[tasks."bump-version"]
description = "Increment the major version (X.y.z)"
run = "bump-my-version bump --new-version $( git-cliff --bump --bumped-version --output - )"

[tasks.git-push]
description = "Push the current branch and related tags"
run = "git push --follow-tags origin HEAD"
